[project]
name = "aubio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nose2>=0.15.1",
    "numpy>=2.0.2",
    "pyaudio>=0.2.14",
    "python-osc>=1.9.3",
    "setuptools>=80.4.0",
]

[dependency-groups]
dev = [
    "aubio",
    "setuptools>=80.4.0",
]

[tool.uv.sources]
aubio = { workspace = true }
